#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinProjektNaZaliczenie.Resource", IsApplication=true)]

namespace XamarinProjektNaZaliczenie
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int MainBackground = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int PhoneBackground = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int SMSBackground = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int WebViewerBackground = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MainPhoneButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MainSMSButton = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int MainWebViewerButton = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int PhoneCallButton = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int PhoneExitButton = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int PhoneNumber = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int SMSContentInput = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int SMSContentText = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int SMSExitButton = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int SMSReceiverInput = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int SMSReceiverText = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int SMSSendButton = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int WebViewerExit = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int WebViewerSearch = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int WebViewerUrl = 2131099662;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			// aapt resource value: 0x7f060010
			public const int webViewContent = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Phone = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SMS = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int WebViewer = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050006
			public const int MainEmpty = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int MainEmpty2 = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int MainNotepad = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int MainPhone = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int MainSMS = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int MainWebViewer = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int PhoneCall = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int PhoneExit = 2131034129;
			
			// aapt resource value: 0x7f05000f
			public const int PhoneNumberHint = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int PhoneNumberText = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int SMSContent = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int SMSContentHint = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int SMSExit = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int SMSReceiver = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int SMSReceiverHint = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int SMSSend = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int WebViewerExit = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int WebViewerHint = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int WebViewerSearch = 2131034131;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
